{% set name = "echopy" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/echopy-{{ version }}.tar.gz
  sha256: fc738c25e5b13212ef9141a5401310c5baa2157aed1d04690b9b651af3f9279c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    # the project doesn't list dependencies, these are taken from depfinder.
    - python >={{ python_min }}
    - ephem
    - geopy
    - numpy
    - pandas
    - scikit-image
    - scipy
    - scikit-fda
    - toml
    - xarray
    - matplotlib-base
    # for reading EK60 raw data and only used for testing.
    # - echolab2

test:
  imports:
    - echopy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-ocean-sounding/echopy
  summary: Fisheries acoustic data processing in Python
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
